name: Build Docker Images

on: push
  # schedule:
  #   - cron: '0 0 * * *' # At 0:00 every day

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Setup QEMU
      #   uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_TOKEN }}
      - name: Build and Push php-apache
        uses: docker/build-push-action@v2
        with:
          file: ./php-apache.dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/chivincent-rosetta/laravel-php:apache
      - name: Build and Push php-cli
        uses: docker/build-push-action@v2
        with:
          file: ./php-cli.dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/chivincent-rosetta/laravel-php:cli
      - name: Build and Push php-fpm
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm.dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/chivincent-rosetta/laravel-php:fpm
      